config/routes.rb
Rails.application.routes.draw do

  resources :merchants

  resources :orders

  resources :goods do
    member do
      post 'select'
    end

    collection do
      get  'cancel'
    end
  end

  root 'console#index'

  devise_for :users , controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :good

  scope :merchant, -> { Merchant.where(id: good.merchant_id) }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /orders
  # GET /orders.json
  def index
    @order_merchants = Order.select(:merchant_id).where(day_at: Date.current).includes(:good).joins(:good).group(:merchant_id).sum(:price)
    @orders = Order.where(day_at: Date.current)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user, :product)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>所有订单</h1>
<p>
    <a href="/">首页</a>
    <a href="/goods">菜谱</a>
    <a href="/merchants">店铺</a>
</p>
<ul>
   <%  @order_merchants.each do | merchant_id, price| %>
       <li>
              订<%= show_merchanrt_name(merchant_id) %> 店一共 <%= price %> 钱
       </li>
   <% end %>
</ul>

<table class="table">
  <thead>
    <tr>
      <th>用户名</th>
      <th>邮箱</th>
      <th>菜名</th>
      <th>店名</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user.try(:name)%></td>
        <td><%= order.user.email %></td>
        <td><%= order.good.name %></td>
        <td><%= order.good.merchant.name %></td>
        <td><%= link_to '删除', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order.product %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>