config/routes.rb
Rails.application.routes.draw do

  resources :merchants

  resources :orders

  resources :goods do
    member do
      post 'select'
    end

    collection do
      get  'cancel'
    end
  end

  root 'console#index'

  devise_for :users , controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :goods
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :address, :phone)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>所有店铺</h1>
<p>
    <a href="/">首页</a>
    <a href="/orders">订单</a>
    <a href="/goods">菜谱</a>
    <%= link_to '增加一个店', new_merchant_path %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>店名</th>
      <th>地址</th>
      <th>联系方式</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.id %></td>
        <td><%= merchant.name %></td>
        <td><%= merchant.address %></td>
        <td><%= merchant.phone %></td>
        <td><%= link_to '查看', merchant %></td>
        <td><%= link_to '编辑', edit_merchant_path(merchant) %></td>
        <td><%= link_to '删除', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/merchants/new.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @merchant.address %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>