config/routes.rb
Rails.application.routes.draw do

  resources :merchants

  resources :orders

  resources :goods do
    member do
      post 'select'
    end

    collection do
      get  'cancel'
    end
  end

  root 'console#index'

  devise_for :users , controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :merchant
  has_many :orders
end

app/controllers/goods_controller.rb
# -*- coding: utf-8 -*-
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy, :select]

  load_and_authorize_resource
  skip_authorize_resource only: [:select, :cancel]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  def cancel
    Order.where(user: current_user, day_at: Date.current).destroy_all
    redirect_to "/", notice: "你取消了今天的订餐"
  end

  def select
    ok = nil # make transaction close faster
    Order.transaction do
      Order.where(user: current_user, day_at: Date.current).destroy_all
      order = Order.new day_at: Date.current
      order.user = current_user
      order.good = @good
      ok = order.save
    end
    if ok
      redirect_to "/", notice: "你选择了 #{@good.merchant.name} 店的 #{@good.name}"
    end
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :describe, :price, :merchant_id)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_area :describe %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :merchant_id %><br>
    <%= f.text_field :merchant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<h1>菜谱</h1>
<p>
    <a href="/">首页</a>
    <a href="/orders">订单</a>
    <a href="/merchants">店铺</a>
    <%= link_to '增加一个菜', new_good_path %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>菜名</th>
      <th>描述</th>
      <th>价格</th>
      <th>店名</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <td><%= good.describe %></td>
        <td><%= good.price %></td>
        <td><%= good.merchant.try(:name) %></td>
        <td><%= link_to '查看', good %></td>
        <td><%= link_to '编辑', edit_good_path(good) %></td>
        <td><%= link_to '删除', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</br>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @good.name %>
</p>

<p>
  <strong>Describe:</strong>
  <%= @good.describe %>
</p>

<p>
  <strong>Price:</strong>
  <%= @good.price %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @good.merchant %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>